// Catálogo de SOLO MATE.
// Para agregar un precio, reemplazá null por un número. Ejemplo: price: 25000.
// Para agregar un producto, duplicá uno de los bloques y cambiá sus datos.
// Las copias cuadradas de las fotos deben conservar el mismo nombre dentro de images-square.
window.SOLO_MATE_PRODUCTS = [
  {
    id: 'mate-criollo',
    name: 'Mate Criollo',
    category: 'Mates',
    subcategory: 'Criollos',
    price: null,
    colors: ['Negro', 'Natural'],
    images: ['images/mate criollo.jpg'],
  },
  {
    id: 'torpedo-avejentado',
    name: 'Torpedo Avejentado',
    category: 'Mates',
    subcategory: 'Torpedos',
    price: null,
    colors: ['Suela'],
    images: ['images/torpedo avejentado.jpg'],
  },
  {
    id: 'imperial-algarrobo',
    name: 'Imperial de Algarrobo',
    category: 'Mates',
    subcategory: 'Imperiales',
    price: null,
    colors: ['Natural', 'Marrón'],
    images: ['images/imperial algarrobo.jpg', 'images/imperial algarrobo marron.jpg'],
  },
  {
    id: 'torpedo-lacre',
    name: 'Torpedo al Lacre',
    category: 'Mates',
    subcategory: 'Torpedos',
    price: null,
    colors: ['Negro', 'Marrón'],
    images: ['images/torpedo al lacre.jpg', 'images/torpedo al lacre marron.jpg'],
  },
  {
    id: 'imperial-criollo',
    name: 'Imperial Criollo',
    category: 'Mates',
    subcategory: 'Imperiales',
    price: null,
    colors: ['Negro'],
    images: ['images/imperial criollo.jpg'],
  },
  {
    id: 'imperial-premium',
    name: 'Imperial Premium',
    category: 'Mates',
    subcategory: 'Imperiales',
    price: null,
    colors: ['Marrón'],
    images: ['images/imperial premium.jpg'],
  },
  {
    id: 'camionero-algarrobo',
    name: 'Camionero de Algarrobo',
    category: 'Mates',
    subcategory: 'Camioneros',
    price: null,
    colors: ['Natural'],
    images: ['images/camionero de algarrobo.jpg'],
  },
  {
    id: 'camionero-premium',
    name: 'Camionero Premium',
    category: 'Mates',
    subcategory: 'Camioneros',
    price: null,
    colors: ['Negro'],
    images: ['images/camionero premium.jpg'],
  },
  {
    id: 'mate-grabado',
    name: 'Mate Grabado',
    category: 'Mates',
    subcategory: 'Grabados',
    price: null,
    colors: ['Negro'],
    images: ['images/mate grabado.jpg'],
  },
  {
    id: 'torpedo-criollo',
    name: 'Torpedo Criollo',
    category: 'Mates',
    subcategory: 'Criollos',
    price: null,
    colors: ['Negro', 'Marrón'],
    images: ['images/torpedo criollo_.jpg', 'images/torpedo criollo.jpg'],
  },
  {
    id: 'mate-ranchero',
    name: 'Mate Ranchero',
    category: 'Mates',
    subcategory: 'Madera',
    price: null,
    colors: ['Natural'],
    images: ['images/mate ranchero.jpg'],
  },
  {
    id: 'torpedo-premium',
    name: 'Torpedo Premium',
    category: 'Mates',
    subcategory: 'Torpedos',
    price: null,
    colors: ['Negro'],
    images: ['images/torpedo premium.jpg'],
  },
  {
    id: 'torpedo-simple',
    name: 'Torpedo Simple',
    category: 'Mates',
    subcategory: 'Torpedos',
    price: null,
    colors: ['Negro'],
    images: ['images/torpedo simple.jpg'],
  },
  {
    id: 'mate-coquito',
    name: 'Mate Coquito',
    category: 'Mates',
    subcategory: 'Madera',
    price: null,
    colors: ['Natural'],
    images: ['images/mate coquito.jpg'],
  },
  {
    id: 'torpedo-rey',
    name: 'Torpedo Rey',
    category: 'Mates',
    subcategory: 'Torpedos',
    price: null,
    colors: ['Negro'],
    images: ['images/torpedo rey.jpg'],
  },
  {
    id: 'canarias-serena',
    name: 'Canarias Serena 500 g',
    category: 'Yerbas',
    subcategory: 'Canarias',
    price: null,
    colors: [],
    images: ['images/canarias serena.jpg'],
  },
  {
    id: 'canarias-tradicional',
    name: 'Canarias Tradicional 500 g',
    category: 'Yerbas',
    subcategory: 'Canarias',
    price: null,
    colors: [],
    images: ['images/canarias tradicional.jpg'],
  },
  {
    id: 'canarias-especial',
    name: 'Canarias Edición Especial 500 g',
    category: 'Yerbas',
    subcategory: 'Canarias',
    price: null,
    colors: [],
    images: ['images/canarias edicion especial.jpg'],
  },
  {
    id: 'baldo-500',
    name: 'Baldo 500 g',
    category: 'Yerbas',
    subcategory: 'Baldo',
    price: null,
    colors: [],
    images: ['images/baldo 500g.jpg'],
  },
  {
    id: 'rei-verde-organica',
    name: 'Rei Verde Orgánica 500 g',
    category: 'Yerbas',
    subcategory: 'Rei Verde',
    price: null,
    colors: [],
    images: ['images/rei verde organica.jpg'],
  },
  {
    id: 'rei-verde-tradicional',
    name: 'Rei Verde Tradicional 500 g',
    category: 'Yerbas',
    subcategory: 'Rei Verde',
    price: null,
    colors: [],
    images: ['images/rei verde tradicional.jpg'],
  },
  {
    id: 'sara-tradicional',
    name: 'Sara Tradicional',
    category: 'Yerbas',
    subcategory: 'Sara',
    price: null,
    colors: [],
    images: ['images/sara tradicional(1).jpg', 'images/sara tradicional.jpg'],
  },
  {
    id: 'verdecita-1kg',
    name: 'Verdecita 1 kg',
    category: 'Yerbas',
    subcategory: 'Verdecita',
    price: null,
    colors: [],
    images: ['images/verdecita 1KG.jpg'],
  },
  {
    id: 'verdecita-500',
    name: 'Verdecita 500 g',
    category: 'Yerbas',
    subcategory: 'Verdecita',
    price: null,
    colors: [],
    images: ['images/verdecita 500g.jpg'],
  },
  {
    id: 'matera-sol-de-mayo',
    name: 'Matera Sol de Mayo',
    category: 'Materas',
    subcategory: 'Materas',
    price: null,
    colors: ['Suela'],
    images: ['images/matera sol de mayo.jpg'],
  },
  {
    id: 'matera-eco-cuero',
    name: 'Matera de Eco Cuero',
    category: 'Materas',
    subcategory: 'Materas',
    price: null,
    colors: ['Negro'],
    images: ['images/matera eco cuero.jpg'],
  },
  {
    id: 'morral-verde',
    name: 'Morral Matero Verde',
    category: 'Materas',
    subcategory: 'Morrales',
    price: null,
    colors: ['Verde'],
    images: ['images/morral matero verde.jpg'],
  },
  {
    id: 'morral-azul',
    name: 'Morral Matero Azul',
    category: 'Materas',
    subcategory: 'Morrales',
    price: null,
    colors: ['Azul'],
    images: ['images/morral matero azul.jpg'],
  },
  {
    id: 'autocebante',
    name: 'Autocebante',
    category: 'Termos',
    subcategory: 'Autocebantes',
    price: null,
    colors: ['Negro'],
    images: [
      'images/autocebante (foto inicial).jpg',
      'images/auto cebante (foto 2) carrusel.jpg',
      'images/auto cebante (foto 3) carrusel.jpg',
    ],
  },
  {
    id: 'termo-grabado',
    name: 'Termo Grabado',
    category: 'Termos',
    subcategory: 'Grabados',
    price: null,
    colors: ['Negro'],
    images: ['images/termo grabado.jpg'],
  },
  {
    id: 'termo-media-manija',
    name: 'Termo Media Manija Negro',
    category: 'Termos',
    subcategory: 'Media manija',
    price: null,
    colors: ['Negro'],
    images: ['images/termo media manija negro.jpg'],
  },
  {
    id: 'set-matero',
    name: 'Set Matero',
    category: 'Combos',
    subcategory: 'Sets',
    price: null,
    colors: ['Negro', 'Suela'],
    images: ['images/foto 2 del set matero para poner en carrusel.jpg'],
  },
  {
    id: 'combo-economico',
    name: 'Combo Económico',
    category: 'Combos',
    subcategory: 'Combos',
    price: null,
    colors: ['Negro'],
    images: ['images/combo economico.jpg'],
  },
  {
    id: 'combo-sol-de-mayo',
    name: 'Combo Sol de Mayo',
    category: 'Combos',
    subcategory: 'Combos',
    price: null,
    colors: ['Suela'],
    images: ['images/combo sol de mayo.jpg'],
  },
  {
    id: 'bombilla-pico-de-loro',
    name: 'Bombilla Pico de Loro',
    category: 'Bombillas',
    subcategory: 'Pico de loro',
    price: null,
    colors: ['Acero'],
    images: ['images/bombilla pico de loro.jpg'],
  },
];
